### ISSUE TITLE
rails db:setup komutundaki "NameError: uninitialized constant Services" hatası

### ISSUE THREAD

**Issue by ecylmz** [omu/nokul#19]
Hatanın alındığı branch = master
RAILS_ENV=production

rails db:setup komutundan gelen hata:

```
Caused by:
NameError: uninitialized constant Services
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/app/lib/tasks/yoksis/fetch_references.rake:36:in `block (2 levels) in <main>'
/app/lib/tasks/yoksis/fetch_references.rake:28:in `block (3 levels) in <main>'
/app/lib/tasks/yoksis/fetch_references.rake:27:in `each'
/app/lib/tasks/yoksis/fetch_references.rake:27:in `block (2 levels) in <main>'
/app/db/seeds.rb:42:in `<main>'
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:551:in `load_seed'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/app/bin/rails:6:in `<main>'
Tasks: TOP => yoksis:fetch_reference
(See full trace by running task with --trace)
```

**Comment by ecylmz** [comment]
@msdundar ilk ve son issue kuralını geç gördüm :( tayga'ya eklerseniz orada açarım.
